name: Cypress Tests

on: 
  push:
    branches:
      - 'automated-test'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: npm install
      # and run all Cypress tests
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          build: npm run build
          start: npx vite --host=localhost --port=5173
          browser: chrome
