name: Cypress Tests

on: 
  push:
    branches:
      - 'automated-test'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  # Install NPM dependencies, cache them correctly

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Remove package-lock.json
        run: |
          cd web
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          cd web
          npm ci --verbose

      # and run all Cypress tests
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          build: npm run build
          start: npx vite --host
